"""Initial schema: 10 tables

Revision ID: 8ed6dd1951d5
Revises: 
Create Date: 2026-04-08 12:30:12.998270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed6dd1951d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('conference', sa.String(length=4), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_type', sa.String(length=30), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('field', sa.String(length=50), nullable=True),
    sa.Column('expected_range', sa.String(length=50), nullable=True),
    sa.Column('actual_value', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=3), nullable=False),
    sa.Column('away_team', sa.String(length=3), nullable=False),
    sa.Column('tipoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_spread', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('total_line', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['away_team'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.String(length=3), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ortg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('drtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('nrtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pace', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'date', 'source')
    )
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.String(length=3), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_on_off',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('on_ortg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('off_ortg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('on_drtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('off_drtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('on_nrtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('off_nrtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('on_minutes', sa.Integer(), nullable=True),
    sa.Column('off_minutes', sa.Integer(), nullable=True),
    sa.Column('minutes_per_game', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('minutes_share', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'date', 'source')
    )
    op.create_table('polymarket_markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=15), nullable=True),
    sa.Column('polymarket_slug', sa.String(length=100), nullable=True),
    sa.Column('polymarket_condition_id', sa.String(length=100), nullable=True),
    sa.Column('yes_price', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('no_price', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('volume', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('liquidity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=15), nullable=True),
    sa.Column('home_adjusted_ortg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('home_adjusted_drtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('home_adjusted_nrtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('away_adjusted_ortg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('away_adjusted_drtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('away_adjusted_nrtg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('projected_spread', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('projected_total', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('home_win_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('spread_cover_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('over_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('schedule_adjustment', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('market_type', sa.String(length=15), nullable=True),
    sa.Column('selection', sa.String(length=100), nullable=True),
    sa.Column('side', sa.String(length=3), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('edge_at_entry', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kelly_fraction', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('result', sa.String(length=5), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('predictions')
    op.drop_table('polymarket_markets')
    op.drop_table('player_on_off')
    op.drop_table('injuries')
    op.drop_table('team_ratings')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('validation_log')
    op.drop_table('teams')
    # ### end Alembic commands ###
