"""create market_snapshots table

Revision ID: c27ff144fa18
Revises: b87ffd7f286a
Create Date: 2026-04-11 01:26:17.080894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27ff144fa18'
down_revision: Union[str, None] = 'b87ffd7f286a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('home_team', sa.String(length=3), nullable=False),
    sa.Column('away_team', sa.String(length=3), nullable=False),
    sa.Column('market_type', sa.String(length=15), nullable=False),
    sa.Column('home_label', sa.String(length=50), nullable=True),
    sa.Column('away_label', sa.String(length=50), nullable=True),
    sa.Column('line', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('polymarket_home_yes', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('polymarket_home_no', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('best_side', sa.String(length=50), nullable=True),
    sa.Column('best_edge', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('verdict', sa.String(length=15), nullable=True),
    sa.Column('kelly_fraction', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('yes_ev', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('no_ev', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'market_type')
    )
    op.create_index(op.f('ix_market_snapshots_game_date'), 'market_snapshots', ['game_date'], unique=False)
    op.create_index(op.f('ix_market_snapshots_game_id'), 'market_snapshots', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_snapshots_game_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_game_date'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
